---
- name: Exercise 4a
  hosts: nxos
  gather_facts: False
  vars:
    command: show interface
  collections:
   - clay584.genie

  tasks:
    - name: Executing command
      nxos_command:
        commands: "{{ command }}"
      register: output

    - name: Display output as string
      debug: 
        var: output
  
    - name: Use Genie to convert to structure data
      set_fact:
        output_struct: "{{ output.stdout[0] | clay584.genie.parse_genie(command=command, os=ansible_network_os) }}"

    - name: Display output as structured data
      debug:
        msg: "{{ output_struct }}"

